name: Test with tox

on:
  push:
    branches: [ "master", "devel" ]
  pull_request:
    types: ["opened", "reopened"]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    - name: Install Deps
      run:
        python -m pip install --upgrade pip
        pip install tox
    - name: Test with Tox in parallel
      run: tox -p
