name: Run Tox

on:
  push:
    branches:
      - main
      - devel
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run:
          python -m pip install --upgrade pip
          # pip install tox
      - name: Run Tox in parallel
        run: tox -p
